---

- name: Install epel-release
  yum:
    name: 'epel-release'
    state: 'present'

- name: Download rpm package for erlang solution
  get_url:
    url: http://packages.erlang-solutions.com/erlang-solutions-1.0-1.noarch.rpm
    dest: /root

- name: Install the erlang solution rpm package and erlang
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - 'erlang-solutions-1.0-1.noarch.rpm'
    - 'erlang'


#- name: Install rpm package for erlang solution
#  command: 'rpm -Uvh /root/erlang-solutions-1.0-1.noarch.rpm'

#- name: Install erlang
#  yum:
#    name: 'erlang'
#    state: present


